### ISSUE TITLE
Book Register has error when book discription not exists

### ISSUE THREAD

**Issue by dskst** [dskst/librarian#15]
```
$ python tasks/library_books.py BookRegister --local-scheduler
Please enter the ISBN code starting with 9 :
9784774198514
ERROR: [pid 94179] Worker Worker(salt=xxxxxxx, workers=1, host=xxxxxxx, username=xxxxxx, pid=xxxxxx) failed    BookRegister(isbn=)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "tasks/library_books.py", line 205, in run
    registration = RegisterDirector(book).build(DataStoreBuilder(entity))
  File "/path/to/dskst/librarian/tasks/director.py", line 43, in build
    builder.add_description(self.book['items'][0]['volumeInfo']['description'])
KeyError: 'description'
```

**Comment by dskst** [comment]
Completed but refactoring remains
